### ISSUE TITLE
Solved all extra challenges

### ISSUE THREAD

**Issue by SemaschkoStanislav** [Teaching-HTL-Leonding/console-chart-quiz-StanislavSemashko#1]
@rstropek  i solved all extra challenges. Can i get extra points.

**Comment by rstropek** [comment]
Note that your `Entry` class would be a good application of C# 9's `record` type. Additionally, you hard-coded the columns of the text file in your `getDictOfAttacks` method. With that, your app is no longer generally usable for analyzing all text files.
